### ISSUE TITLE
provide symbol information

### ISSUE THREAD

**Issue by garymm** [MrKou47/thrift-syntax-support#15]
Thanks for the extension!
Would be great to have symbol information too.
A guide on how to do this: https://stackoverflow.com/questions/46045245/how-to-enable-go-to-symbol-with-a-custom-language-in-vscode

**Comment by MrKou47** [comment]
Thanks for your advice and kind solution. Now you could update this extension to the latest version to enjoy this feature :)

**Comment by garymm** [comment]
Awesome! For the record, fixed by https://github.com/MrKou47/thrift-syntax-support/commit/aeeb6b412199314a2ddded0ad6c2346c669414d2
