### ISSUE TITLE
使用某个具体的枚举值时不能跳转至定义处

### ISSUE THREAD

**Issue by windard** [MrKou47/thrift-syntax-support#4]
```

enum Week {
    Monday = 1
    Tuesday = 2
    Wednesday = 3
    Thursday = 4
    Friday = 5
    Saturday = 6
    Sunday = 7
}

const Week today = Week.Thursday

```

比如说这样的的一个常量 `today`， 点击类型定义的 `Week` 还能点击跳转到定义处，但是点击常量值 `Week.Thursday` 就没有自动跳转。

**Comment by MrKou47** [comment]
看上去是第三方parser的问题，我处理下

**Comment by MrKou47** [comment]
@windard 0.0.4 已发布，支持了此功能

**Comment by windard** [comment]
大佬，那你会写 Java 么？😂，帮忙看下 jetbrain 中同样的问题。
https://github.com/fkorotkov/intellij-thrift/issues/11
