### ISSUE TITLE
Add to Marketplace?

### ISSUE THREAD

**Issue by zicklag** [MrKou47/thrift-syntax-support#9]
What do you think about adding this plugin to the marketplace. It looks better and more recently updated than any of the other plugins on the VSCode marketplace. :)

**Comment by MrKou47** [comment]
This plugin has already published in the VSCode marketplace.You can find it via https://marketplace.visualstudio.com/items?itemName=mrkou47.thrift-syntax-support 😄️

**Comment by zicklag** [comment]
:man_facepalming: Whoops. My bad. I must have gotten mixed up. :)
